name: CI

on:
  push:
    branches: [ master ]

env:
  BUCKET: pedroksty.com

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
        
    - name: Install dependecies
      run: yarn install
      
    - name: build 
      run: yarn build
      
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        project_id: ${{ secrets.GCP_PROJECT }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
        
    - name: Upload Files to bucket
      run: gsutil -m rsync -R .build gs://"$BUCKET"
    
    - name: Allow public access
      run: gsutil -m acl ch -R -u AllUsers:R gs://"$BUCKET"
      
    - name: Set Cacha-control
      run: gsutil -m setmeta -h "Cache-Control:public, max-age=15768000" gs://"$BUCKET"/**/*.{css,js}
      
    - name: Set Cacha-control
      run: gsutil setmeta -h "Cache-Control:public, no-store" gs://"$BUCKET"/index.html
      
    

 


